openapi: 3.0.3
info:
  title: API de Gerenciamento de Usuários
  version: 1.0.0
  description: Aplicação que realiza o gerenciamento de usuários e restaurantes.

tags:
  - name: Cliente
    description: Endpoints para gerenciamento de clientes
  - name: Restaurante
    description: Endpoints para gerenciamento de restaurantes

paths:
  /clientes:
    post:
      tags:
        - Cliente
      summary: Criar um novo cliente
      description: Criar um novo cliente, com dados pessoais.
      operationId: InserirUsuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
      responses:
        '201':
          description: Usuário criado com sucesso
        '400':
          description: Requisição inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Usuário ou documento já existente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /restaurantes:
    post:
      tags:
        - Restaurante
      summary: Criar um novo restaurante
      description: Criar um novo restaurante, com dados pessoais.
      operationId: InserirRestaurante
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
      responses:
        '201':
          description: Restaurante criado com sucesso
        '400':
          description: Requisição inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Usuário ou documento já existente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Usuario:
      type: object
      properties:
        nome:
          type: string
          example: João da Silva
        email:
          type: string
          format: email
          example: joao@email.com
        endereco:
          type: string
          example: Rua das Flores, 123
        telefone:
          type: string
          example: "+55 11 91234-5678"
        usuario:
          type: string
          example: joaosilva123
      required:
        - nome
        - email
        - endereco
        - telefone
        - usuario

    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          example: "2025-05-14T15:42:00Z"
        status:
          type: integer
          example: 404
        error:
          type: string
          example: "Not Found"
        message:
          type: string
          example: "Usuário não encontrado"
        path:
          type: string
          example: "/ms-usuario/v1/usuario"